Task
sassamori/quelcode-cakephp pull request #1
Opened 2020-12-17 10:46 UTC by sassamori

2020-12-18 10:28 UTC, n06Ar requested changes
レビューしました。
ご確認をお願いします。

2020-12-18 10:28 UTC, n06Ar commented on html/mycakeapp/composer.json
> +        "josegonzalez/cakephp-upload": "4.0.2",
Slackのやり取りで、バリデーションでは使用しなくなった気がしたので確認です。
バリデーション以外でこのプラグインは使っていますか？

2020-12-18 10:28 UTC, n06Ar commented on html/mycakeapp/src/Controller/AuctionController.php
> +                if(is_uploaded_file($upload_file['tmp_name'])){
確認ですが、テーブルのインサートに失敗した場合も保存する実装で問題ないでしょうか？
現状失敗しようが画像を保存する実装だったので確認したい意図です。

2020-12-18 10:28 UTC, n06Ar commented on html/mycakeapp/src/Controller/AuctionController.php
> +            }catch(Exception $e){
tryのなかに`$this->Biditems->save($biditem)`に入っていないので、保存に失敗してもレコードのインサートが実行されますが問題ないでしょうか？

2020-12-18 12:19 UTC, sassamori commented on html/mycakeapp/composer.json
> +        "josegonzalez/cakephp-upload": "4.0.2",
validation以外で使ってないはずです。
ただ、一度消してみた（requireから消してcomposer update）ところ、fatal errorで表示がうまくいきませんでした…。

2020-12-19 02:31 UTC, n06Ar requested changes
コメントしました！

2020-12-19 02:31 UTC, n06Ar commented on html/mycakeapp/src/Controller/AuctionController.php
> +                    move_uploaded_file($upload_file['tmp_name'],$filePath);
実装としてはこんな感じでOKです
```php
if(is_uploaded_file($upload_file['tmp_name']) && move_uploaded_file($upload_file['tmp_name'],$filePath)){
    // 成功時
} else {
    // 失敗時
    throw new \Exception('失敗しました。');
}
```

2020-12-19 02:31 UTC, n06Ar commented on html/mycakeapp/src/Controller/AuctionController.php
> +                        $connection->rollback();
116行目から120行目まではcatchで良いです。

2020-12-19 03:02 UTC, n06Ar approved these changes
LGTM!

2020-12-19 03:05 UTC, merged